### PR TITLE
Added option to prefix postfix resized images

### PR DESCRIPTION
**Pull request by Feroks**
I needed to Tint same icon into multiple colors. Since file name is the same, only last TintColor definition persists.
By adding prefixes or postfixes we can alter file name, which will solve overwrite problem.

### CODE REVIEW

**Review by mattleibow — CHANGES_REQUESTED** [review]
Not that this is a bad PR, but I think this can also be solved by actually supporting the `Link="xxx"` feature of MSBuild.

However, this is actually not supported right now as resizetizer ignores this attribute.

I am working on a PR now, and will link.

**Comment by mattleibow** [comment]
I think this might be a more generic approach: https://github.com/Redth/ResizetizerNT/pull/55

**Comment by Feroks** [comment]
Good point, it does seem more convenient to use.
However, does your PR support wildcards such as: `%(RecursiveDir)`, `%(FileName)`, `%(Extension)` like `Link` does for regular files? I include icons by directories to avoid inflating .csporj file and this way you can easily specify how to adjust name for all files.

**Comment by mattleibow** [comment]
> However, does your PR support wildcards such as: `%(RecursiveDir)`, `%(FileName)`, `%(Extension)` like `Link` does for regular files? 

Let me try as I think it should.

**Comment by mattleibow** [comment]
Seems it does:

```xml
  <ItemGroup>
    <SharedImage Include="images\**\*" Link="%(RecursveDir)new_name_%(FileName)%(Extension)" />
  </ItemGroup>
```

| images | output |
| image | image |


This is because these values are evaluated before it even gets to our tasks.

**Comment by Feroks** [comment]
Great!
Then this PR can be closed.

**Comment by mattleibow** [comment]
Awesome! Thanks for raising the idea! Great to get all this in!

**Pull request closed without merging**
